export const ROUTES = {
	HOME: '/',
	PRODUCT: '/product',
	DIGITAL_WAREHOUSING: '/product/digital-warehousing',
	OPT_SHIPPING: '/product/opt-shipping',
	CLOUD_WMS: '/product/cloud-wms',
	ECOMMERCE_WMS: '/product/ecommerce-wms',
	SCALEABLE_WMS: '/product/scaleable-wms',
	ANALYTICS: '/product/analytics',
	ORDER: '/solution/order',
	RECEIVE: '/solution/receive',
	SHIPPING: '/solution/shipping',
	INVENTORY: '/solution/inventory',
	CUSTOMER: '/customer',
	CUSTOMER_CASE_1: '/customer/case-1',
	CUSTOMER_CASE_3: '/customer/case-3',
	CONTACT: '/contact',
	TERMS: '/policy/terms-of-use',
	POLICY: '/policy/privacy-policy',
};
